### ISSUE TITLE
Redesign graphics renderer

### ISSUE THREAD

**Issue by fapablazacl** [fapablazacl/XE#3]
### User Story
**As a** Developer
**I want** to redesign the XE::Graphics::GraphicsDevice interface to a asynchronous, queued style
**so that** I can push more visuals into the screen.

### Tasks
- [ ] Investigate State of the Art APIs, like Vulkan, Metal and Direct3D 12
- [ ] Extract the Domain Model of their core abstraction facilities, like Queues. Swap Chains, etc.
- [ ] Refactor the XE.Graphics module
- [ ] Reimplement the XE.Graphics.GL module with the new facilities.
